export class dnd5eProvider {
	classes = {};

	async getFilters() {
		await this.getClasses();
	}

	async getClasses() {
		const subclasses = {};
		for (let pack of game.packs) {
			if (pack.documentName === "Item") {
				const indexes = await pack.getIndex({ fields: ["system.identifier", "system.classIdentifier"] });
				const classes = indexes.filter((entry) => entry.type === "class" && entry.system.identifier);
				if (classes.length) {
					classes.map((entry) => {
						return {
							label: entry.name,
							identifier: entry.system.identifier
						};
					})
					.forEach((c) => {
						this.classes[c.identifier] = {
							label: c.label,
							subclasses: {}
						};
					});
				}
				const _subclasses = indexes.filter((entry) => entry.type === "subclass" && entry.system.classIdentifier);
				if (_subclasses.length) {
					_subclasses.map((entry) => {
							return {
								name: entry.name,
								identifier: entry.system.identifier,
								classId: entry.system.classIdentifier
							};
						})
						.forEach((subclass) => {
							if (subclasses[subclass.classId]) {
								subclasses[subclass.classId].subclasses[subclass.identifier] = subclass.name;
							} else {
								subclasses[subclass.classId] = {
									subclasses: {
										[subclass.identifier]: subclass.name
									}
								};
							}
						});
				}
			}
		}
		this.classes = foundry.utils.mergeObject(this.classes, subclasses);
		this.classes = Object.fromEntries(
			Object.entries(this.classes).filter(([classId, classData]) => classData.label)
		);
	}

	static get classList() {
		let list = {
			abidalzimshorridwilting: "sorcerer,wizard",
			absorbelements: "artificer,druid,ranger,sorcerer,wizard",
			arcaneweapon: "artificerrevisited",
			acidsplash: "artificer,sorcerer,wizard,artificerrevisited",
			aganazzarsscorcher: "sorcerer,wizard",
			aid: "artificer,bard,cleric,paladin,artificer,artificerrevisited",
			alarm: "artificer,ranger,wizard,artificer,artificerrevisited",
			alterself: "artificer,sorcerer,wizard,artificer,artificerrevisited",
			animalfriendship: "bard,druid,ranger",
			animalmessenger: "bard,druid,ranger",
			animalshapes: "druid",
			animatedead: "cleric,wizard",
			animateobjects: "artificer,bard,sorcerer,wizard,artificerrevisited",
			antilifeshell: "druid",
			antimagicfield: "cleric,wizard",
			antipathysympathy: "bard,druid,wizard",
			arcaneeye: "artificer,wizard,artificer,artificerrevisited",
			arcanegate: "sorcerer,warlock,wizard",
			arcanelock: "artificer,wizard,artificer,artificerrevisited",
			armorofagathys: "warlock",
			armsofhadar: "warlock",
			astralprojection: "cleric,warlock,wizard",
			augury: "cleric",
			auraoflife: "paladin",
			auraofpurity: "paladin",
			auraofvitality: "paladin",
			awaken: "bard,druid",
			bane: "bard,cleric",
			banishingsmite: "paladin",
			banishment: "cleric,paladin,sorcerer,warlock,wizard",
			barkskin: "druid,ranger",
			beaconofhope: "cleric",
			beastbond: "druid,ranger",
			beastsense: "druid,ranger",
			bestowcurse: "bard,cleric,wizard",
			bigbyshand: "artificer,wizard,artificerrevisited",
			arcanehand: "wizard,artificerrevisited",
			bladebarrier: "cleric",
			bladeward: "bard,sorcerer,warlock,wizard",
			bless: "cleric,paladin",
			bladeofdisaster: "sorcerer,warlock,wizard",
			blight: "druid,sorcerer,warlock,wizard",
			blindingsmite: "paladin",
			blindnessdeafness: "bard,cleric,sorcerer,wizard",
			blink: "artificer,sorcerer,wizard,artificer,artificerrevisited",
			blur: "artificer,sorcerer,wizard,artificer,artificerrevisited",
			bonesoftheearth: "druid",
			boomingblade: "artificer,sorcerer,warlock,wizard",
			brandingsmite: "paladin",
			burninghands: "sorcerer,wizard",
			calllightning: "druid",
			calmemotions: "bard,cleric",
			catapult: "artificer,sorcerer,wizard",
			catnap: "artificer,bard,sorcerer,wizard",
			causefear: "warlock,wizard",
			ceremony: "cleric,paladin",
			chainlightning: "sorcerer,wizard",
			chaosbolt: "sorcerer",
			charmmonster: "bard,druid,sorcerer,warlock,wizard",
			charmperson: "bard,druid,sorcerer,warlock,wizard",
			chilltouch: "sorcerer,warlock,wizard",
			chromaticorb: "sorcerer,wizard",
			circleofdeath: "sorcerer,warlock,wizard",
			circleofpower: "paladin",
			clairvoyance: "bard,cleric,sorcerer,wizard",
			clone: "wizard",
			cloudofdaggers: "bard,sorcerer,warlock,wizard",
			cloudkill: "sorcerer,wizard",
			colorspray: "bard,sorcerer,wizard",
			command: "bard,cleric,paladin",
			commune: "cleric",
			communewithnature: "druid,ranger",
			compelledduel: "paladin",
			comprehendlanguages: "bard,sorcerer,warlock,wizard",
			compulsion: "bard",
			coneofcold: "sorcerer,wizard",
			confusion: "bard,druid,sorcerer,wizard",
			conjureanimals: "druid,ranger",
			conjurebarrage: "ranger",
			conjurecelestial: "cleric",
			conjureelemental: "druid,wizard",
			conjurefey: "druid,warlock",
			conjureminorelementals: "druid,wizard",
			conjurevolley: "ranger",
			conjurewoodlandbeings: "druid,ranger",
			contactotherplane: "warlock,wizard",
			contagion: "cleric,druid",
			contingency: "wizard",
			continualflame: "artificer,cleric,wizard,artificer,artificerrevisited",
			controlflames: "druid,sorcerer,wizard",
			controlwater: "cleric,druid,wizard",
			controlweather: "cleric,druid,wizard",
			controlwinds: "druid,sorcerer,wizard",
			cordonofarrows: "ranger",
			counterspell: "sorcerer,warlock,wizard",
			createbonfire: "artificer,druid,sorcerer,warlock,wizard",
			createfoodandwater: "artificer,cleric,paladin",
			createhomunculus: "wizard",
			createmagen: "wizard",
			createundead: "cleric,warlock,wizard",
			createordestroywater: "cleric,druid",
			creation: "artificer,sorcerer,wizard,artificerrevisited",
			crownofmadness: "bard,sorcerer,warlock,wizard",
			crownofstars: "sorcerer,warlock,wizard",
			crusadersmantle: "paladin",
			curewounds: "artificer,bard,cleric,druid,paladin,ranger,artificer,artificerrevisited",
			dancinglights: "artificer,bard,sorcerer,wizard,artificerrevisited",
			dansemacabre: "warlock,wizard",
			darkness: "sorcerer,warlock,wizard",
			darkvision: "artificer,druid,ranger,sorcerer,wizard,artificer,artificerrevisited",
			dawn: "cleric,wizard",
			daylight: "cleric,druid,paladin,ranger,sorcerer",
			deathward: "cleric,paladin,artificer",
			delayedblastfireball: "sorcerer,wizard",
			demiplane: "warlock,wizard",
			destructivewave: "paladin",
			detectevilandgood: "cleric,paladin",
			detectmagic: "artificer,bard,cleric,druid,paladin,ranger,sorcerer,wizard,artificerrevisited",
			detectpoisonanddisease: "cleric,druid,paladin,ranger",
			detectthoughts: "bard,sorcerer,wizard",
			dimensiondoor: "bard,sorcerer,warlock,wizard",
			disguiseself: "artificer,bard,sorcerer,wizard,artificer,artificerrevisited",
			disintegrate: "sorcerer,wizard",
			dispelevilandgood: "cleric,paladin",
			dispelmagic: "artificer,bard,cleric,druid,paladin,sorcerer,warlock,wizard,artificerrevisited",
			dissonantwhispers: "bard",
			distortvalue: "bard,sorcerer,warlock,wizard",
			divination: "cleric",
			divinefavor: "paladin",
			divineword: "cleric",
			dominatebeast: "druid,sorcerer",
			dominatemonster: "bard,sorcerer,warlock,wizard",
			dominateperson: "bard,sorcerer,wizard",
			dragonsbreath: "sorcerer,wizard",
			drawmijsinstantsummons: "wizard",
			dreamoftheblueveil: "bard,sorcerer,warlock,wizard",
			dream: "bard,warlock,wizard",
			druidgrove: "druid",
			druidcraft: "druid",
			dustdevil: "druid,sorcerer,wizard",
			earthtremor: "bard,druid,sorcerer,wizard",
			earthbind: "druid,sorcerer,warlock,wizard",
			earthquake: "cleric,druid,sorcerer",
			eldritchblast: "warlock",
			elementalbane: "artificer,druid,warlock,wizard",
			elementalweapon: "artificer,paladin,artificerrevisited",
			enemiesabound: "bard,sorcerer,warlock,wizard",
			enervation: "sorcerer,warlock,wizard",
			enhanceability: "artificer,bard,cleric,druid,sorcerer,artificer,artificerrevisited",
			enlargereduce: "artificer,bard,sorcerer,wizard,artificer,artificerrevisited",
			ensnaringstrike: "ranger",
			entangle: "druid",
			enthrall: "bard,warlock",
			eruptingearth: "druid,sorcerer,wizard",
			etherealness: "bard,cleric,sorcerer,warlock,wizard",
			evardsblacktentacles: "wizard",
			blacktentacles: "wizard",
			expeditiousretreat: "artificer,sorcerer,warlock,wizard,artificer,artificerrevisited",
			eyebite: "bard,sorcerer,warlock,wizard",
			fabricate: "artificer,wizard,artificer,artificerrevisited",
			faeriefire: "artificer,bard,druid",
			falselife: "artificer,sorcerer,wizard,artificer,artificerrevisited",
			farstep: "sorcerer,warlock,wizard",
			fastfriends: "bard,cleric,wizard",
			fear: "bard,sorcerer,warlock,wizard",
			featherfall: "artificer,bard,sorcerer,wizard",
			feeblemind: "bard,druid,warlock,wizard",
			feigndeath: "bard,cleric,druid,wizard",
			findfamiliar: "wizard",
			findgreatersteed: "paladin",
			findsteed: "paladin",
			findtraps: "cleric,druid,ranger",
			findthepath: "bard,cleric,druid",
			fingerofdeath: "sorcerer,warlock,wizard",
			firebolt: "artificer,sorcerer,wizard,artificerrevisited",
			fireshield: "wizard",
			firestorm: "cleric,druid,sorcerer",
			fireball: "sorcerer,wizard",
			flamearrows: "artificer,druid,ranger,sorcerer,wizard",
			flameblade: "druid",
			flamestrike: "cleric",
			flamingsphere: "druid,wizard",
			fleshtostone: "warlock,wizard",
			fly: "artificer,sorcerer,warlock,wizard,artificer,artificerrevisited",
			fogcloud: "druid,ranger,sorcerer,wizard",
			forbiddance: "cleric",
			forcecage: "bard,warlock,wizard",
			foresight: "bard,druid,warlock,wizard",
			freedomofmovement: "artificer,bard,cleric,druid,ranger,artificer,artificerrevisited",
			friends: "bard,sorcerer,warlock,wizard",
			frostbite: "artificer,druid,sorcerer,warlock,wizard",
			frostfingers: "wizard",
			gaseousform: "sorcerer,warlock,wizard,artificer,artificerrevisited",
			gate: "cleric,sorcerer,wizard",
			geas: "bard,cleric,druid,paladin,wizard",
			gentlerepose: "cleric,wizard",
			giantinsect: "druid",
			giftofgab: "bard,wizard",
			glibness: "bard,warlock",
			globeofinvulnerability: "sorcerer,wizard",
			glyphofwarding: "artificer,bard,cleric,wizard,artificer,artificerrevisited",
			goodberry: "druid,ranger",
			graspingvine: "druid,ranger",
			grease: "artificer,wizard,artificerrevisited",
			greaterinvisibility: "bard,sorcerer,wizard",
			greaterrestoration: "artificer,bard,cleric,druid,artificerrevisited",
			greenflameblade: "artificer,sorcerer,warlock,wizard",
			guardianoffaith: "cleric",
			guardianofnature: "druid,ranger",
			guardsandwards: "bard,wizard",
			guidance: "artificer,cleric,druid,artificerrevisited",
			guidingbolt: "cleric",
			gust: "druid,sorcerer,wizard",
			gustofwind: "druid,sorcerer,wizard",
			hailofthorns: "ranger",
			hallow: "cleric",
			hallucinatoryterrain: "bard,druid,warlock,wizard",
			harm: "cleric",
			haste: "artificer,sorcerer,wizard,artificer,artificerrevisited",
			heal: "cleric,druid",
			healingspirit: "druid,ranger",
			healingword: "bard,cleric,druid",
			heatmetal: "artificer,bard,druid,artificerrevisited",
			hellishrebuke: "warlock",
			heroesfeast: "bard,cleric,druid",
			heroism: "bard,paladin",
			hex: "warlock",
			holdmonster: "bard,sorcerer,warlock,wizard",
			holdperson: "bard,cleric,druid,sorcerer,warlock,wizard",
			holyaura: "cleric",
			holyweapon: "cleric,paladin",
			hungerofhadar: "warlock",
			huntersmark: "ranger",
			hypnoticpattern: "bard,sorcerer,warlock,wizard",
			iceknife: "druid,sorcerer,wizard",
			icestorm: "druid,sorcerer,wizard",
			identify: "artificer,bard,wizard,artificerrevisited",
			illusorydragon: "wizard",
			illusoryscript: "bard,warlock,wizard",
			immolation: "sorcerer,wizard",
			imprisonment: "warlock,wizard",
			incendiarycloud: "sorcerer,wizard",
			incitegreed: "cleric,warlock,wizard",
			infernalcalling: "warlock,wizard",
			infestation: "druid,sorcerer,warlock,wizard",
			inflictwounds: "cleric",
			insectplague: "cleric,druid,sorcerer",
			instantsummons: "wizard",
			intellectfortress: "artificer,bard,sorcerer,warlock,wizard",
			investitureofflame: "druid,sorcerer,warlock,wizard",
			investitureofice: "druid,sorcerer,warlock,wizard",
			investitureofstone: "druid,sorcerer,warlock,wizard",
			investitureofwind: "druid,sorcerer,warlock,wizard",
			invisibility: "artificer,bard,sorcerer,warlock,wizard,artificer,artificerrevisited",
			invulnerability: "wizard",
			jimsglowingcoin: "wizard",
			jimsmagicmissile: "wizard",
			jump: "artificer,druid,ranger,sorcerer,wizard,artificer,artificerrevisited",
			knock: "bard,sorcerer,wizard",
			legendlore: "bard,cleric,wizard",
			leomundssecretchest: "artificer,wizard,artificer,artificerrevisited",
			leomundstinyhut: "bard,wizard",
			lesserrestoration: "artificer,bard,cleric,druid,paladin,ranger,artificer,artificerrevisited",
			levitate: "artificer,sorcerer,wizard,artificerrevisited",
			lifetransference: "cleric,wizard",
			light: "artificer,bard,cleric,sorcerer,wizard,artificerrevisited",
			lightningarrow: "ranger",
			lightningbolt: "sorcerer,wizard",
			lightninglure: "artificer,sorcerer,warlock,wizard",
			locateanimalsorplants: "bard,druid,ranger",
			locatecreature: "bard,cleric,druid,paladin,ranger,wizard",
			locateobject: "bard,cleric,druid,paladin,ranger,wizard",
			longstrider: "artificer,bard,druid,ranger,wizard,artificer,artificerrevisited",
			maddeningdarkness: "warlock,wizard",
			maelstrom: "druid",
			magearmor: "sorcerer,wizard",
			magehand: "artificer,bard,sorcerer,warlock,wizard,artificerrevisited",
			magiccircle: "cleric,paladin,warlock,wizard",
			magicjar: "wizard",
			magicmissile: "sorcerer,wizard",
			magicmouth: "artificer,bard,wizard,artificerrevisited",
			magicstone: "artificer,druid,warlock",
			magicweapon: "artificer,paladin,wizard,artificer,artificerrevisited",
			majorimage: "bard,sorcerer,warlock,wizard",
			masscurewounds: "bard,cleric,druid",
			massheal: "cleric",
			masshealingword: "bard,cleric",
			masspolymorph: "bard,sorcerer,wizard",
			masssuggestion: "bard,sorcerer,warlock,wizard",
			maximiliansearthengrasp: "sorcerer,wizard",
			maze: "wizard",
			meldintostone: "cleric,druid",
			melfsacidarrow: "wizard",
			melfsminutemeteors: "sorcerer,wizard",
			acidarrow: "wizard",
			mending: "artificer,bard,cleric,druid,sorcerer,wizard,artificerrevisited",
			mentalprison: "sorcerer,warlock,wizard",
			message: "artificer,bard,sorcerer,wizard,artificerrevisited",
			meteorswarm: "sorcerer,wizard",
			mightyfortress: "wizard",
			mindblank: "bard,wizard",
			mindsliver: "sorcerer,warlock,wizard",
			mindspike: "sorcerer,warlock,wizard",
			minorillusion: "bard,sorcerer,warlock,wizard",
			miragearcane: "bard,druid,wizard",
			mirrorimage: "bard,sorcerer,warlock,wizard",
			mislead: "bard,wizard",
			mistystep: "sorcerer,warlock,wizard",
			modifymemory: "bard,wizard",
			moldearth: "druid,sorcerer,wizard",
			moonbeam: "druid",
			mordenkainensfaithfulhound: "artificer,wizard,artificer,artificerrevisited",
			motivationalspeech: "bard,cleric",
			faithfulhound: "wizard,artificer,artificerrevisited",
			mordenkainensmagnificentmansion: "bard,wizard",
			magnificentmansion: "bard,wizard",
			mordenkainensprivatesanctum: "artificer,wizard,artificer,artificerrevisited",
			mordenkainenssword: "bard,wizard",
			arcanesword: "bard,wizard",
			moveearth: "druid,sorcerer,wizard",
			negativeenergyflood: "warlock,wizard",
			nondetection: "bard,ranger,wizard",
			nystulsmagicaura: "wizard",
			arcanistsmagicaura: "wizard",
			otilukesfreezingsphere: "wizard",
			otilukesresilientsphere: "artificer,wizard,artificer,artificerrevisited",
			ottosirresistibledance: "bard,wizard",
			passwithouttrace: "druid,ranger",
			passwall: "wizard",
			phantasmalforce: "bard,sorcerer,wizard",
			phantasmalkiller: "bard,wizard",
			phantomsteed: "wizard",
			planarally: "cleric",
			planarbinding: "bard,cleric,druid,wizard",
			planeshift: "cleric,druid,sorcerer,warlock,wizard",
			plantgrowth: "bard,druid,ranger",
			poisonspray: "artificer,druid,sorcerer,warlock,wizard,artificerrevisited",
			polymorph: "bard,druid,sorcerer,wizard",
			powerwordheal: "bard",
			powerwordkill: "bard,sorcerer,warlock,wizard",
			powerwordpain: "sorcerer,warlock,wizard",
			powerwordstun: "bard,sorcerer,warlock,wizard",
			prayerofhealing: "cleric",
			prestidigitation: "artificer,bard,sorcerer,warlock,wizard,artificerrevisited",
			primalsavagery: "druid",
			primordialward: "druid",
			prismaticspray: "bard,sorcerer,wizard",
			prismaticwall: "bard,wizard",
			produceflame: "druid",
			programmedillusion: "bard,wizard",
			projectimage: "bard,wizard",
			protectionfromenergy: "artificer,cleric,druid,ranger,sorcerer,wizard,artificer,artificerrevisited",
			protectionfromevilandgood: "cleric,paladin,warlock,wizard",
			protectionfrompoison: "artificer,cleric,druid,paladin,ranger,artificer,artificerrevisited",
			psychicscream: "bard,sorcerer,warlock,wizard",
			purifyfoodanddrink: "artificer,cleric,druid,paladin",
			pyrotechnics: "artificer,bard,sorcerer,wizard",
			raisedead: "bard,cleric,paladin",
			rarystelepathicbond: "bard,wizard",
			rayofenfeeblement: "warlock,wizard",
			rayoffrost: "artificer,sorcerer,wizard,artificerrevisited",
			rayofsickness: "sorcerer,wizard",
			regenerate: "bard,cleric,druid",
			reincarnate: "druid",
			removecurse: "cleric,paladin,warlock,wizard",
			resistance: "artificer,cleric,druid,artificerrevisited",
			resurrection: "bard,cleric",
			reversegravity: "druid,sorcerer,wizard",
			revivify: "artificer,cleric,paladin,artificer,artificerrevisited",
			ropetrick: "artificer,wizard,artificer,artificerrevisited",
			sacredflame: "cleric",
			sanctuary: "artificer,cleric,artificer,artificerrevisited",
			scatter: "sorcerer,warlock,wizard",
			scorchingray: "sorcerer,wizard",
			scrying: "bard,cleric,druid,warlock,wizard",
			searingsmite: "paladin",
			seeinvisibility: "artificer,bard,sorcerer,wizard,artificerrevisited",
			seeming: "bard,sorcerer,wizard",
			sending: "bard,cleric,wizard",
			sequester: "wizard",
			shadowblade: "sorcerer,warlock,wizard",
			shadowofmoil: "warlock",
			shapewater: "druid,sorcerer,wizard",
			shapechange: "druid,wizard",
			shatter: "bard,sorcerer,warlock,wizard",
			shield: "sorcerer,wizard",
			shieldoffaith: "cleric,paladin,artificer,artificerrevisited",
			shillelagh: "druid",
			shockinggrasp: "artificer,sorcerer,wizard,artificerrevisited",
			sickeningradiance: "sorcerer,warlock,wizard",
			silence: "bard,cleric,ranger",
			silentimage: "bard,sorcerer,wizard",
			simulacrum: "wizard",
			skillempowerment: "artificer,bard,sorcerer,wizard",
			skywrite: "artificer,bard,druid,wizard",
			sleep: "bard,sorcerer,wizard",
			sleetstorm: "druid,sorcerer,wizard",
			slow: "bard,sorcerer,wizard",
			snare: "artificer,druid,ranger,wizard",
			snillocssnowballswarm: "sorcerer,wizard",
			soulcage: "warlock,wizard",
			sparethedying: "artificer,cleric,artificerrevisited",
			speakwithanimals: "bard,druid,ranger",
			speakwithdead: "bard,cleric",
			speakwithplants: "bard,druid,ranger",
			spiderclimb: "artificer,sorcerer,warlock,wizard,artificer,artificerrevisited",
			spikegrowth: "druid,ranger",
			spiritguardians: "cleric",
			spiritualweapon: "cleric",
			spiritshroud: "cleric,paladin,warlock,wizard",
			staggeringsmite: "paladin",
			steelwindstrike: "ranger,wizard",
			stinkingcloud: "bard,sorcerer,wizard",
			stoneshape: "artificer,cleric,druid,wizard,artificer,artificerrevisited",
			stoneskin: "artificer,druid,ranger,sorcerer,wizard,artificer,artificerrevisited",
			stormofvengeance: "druid",
			stormsphere: "sorcerer,wizard",
			suggestion: "bard,sorcerer,warlock,wizard",
			summonaberration: "warlock,wizard",
			summonbeast: "druid,ranger",
			summoncelestial: "cleric,paladin",
			summonconstruct: "artificer,wizard",
			summonelemental: "druid,ranger,wizard",
			summonfey: "druid,ranger,warlock,wizard",
			summonfiend: "warlock,wizard",
			summongreaterdemon: "warlock,wizard",
			summonlesserdemons: "warlock,wizard",
			summonshadowspawn: "warlock,wizard",
			summonundead: "warlock,wizard",
			sunbeam: "druid,sorcerer,wizard",
			sunburst: "druid,sorcerer,wizard",
			swiftquiver: "ranger",
			swordburst: "artificer,sorcerer,warlock,wizard",
			synapticstatic: "bard,sorcerer,warlock,wizard",
			symbol: "bard,cleric,wizard",
			tashascausticbrew: "artificer,sorcerer,wizard",
			tashashideouslaughter: "bard,wizard",
			hideouslaughter: "bard,wizard",
			tashasmindwhip: "sorcerer,wizard",
			tashasotherworldlyguise: "sorcerer,warlock,wizard",
			telekinesis: "sorcerer,wizard",
			telepathy: "wizard",
			teleport: "bard,sorcerer,wizard",
			teleportationcircle: "bard,sorcerer,wizard",
			templeofthegods: "cleric",
			tensersfloatingdisk: "wizard",
			tensersfloatingdisc: "wizard",
			tenserstransformation: "wizard",
			floatingdisc: "wizard",
			thaumaturgy: "cleric",
			thornwhip: "artificer,druid,artificerrevisited",
			thunderstep: "sorcerer,warlock,wizard",
			thunderclap: "artificer,bard,druid,sorcerer,warlock,wizard",
			thunderoussmite: "paladin",
			thunderwave: "bard,druid,sorcerer,wizard",
			tidalwave: "druid,sorcerer,wizard",
			timestop: "sorcerer,wizard",
			tinyservant: "artificer,wizard",
			tollthedead: "cleric,warlock,wizard",
			tongues: "bard,cleric,sorcerer,warlock,wizard",
			transmuterock: "artificer,druid,wizard",
			transportviaplants: "druid",
			treestride: "druid,ranger",
			truepolymorph: "bard,warlock,wizard",
			trueresurrection: "cleric,druid",
			trueseeing: "bard,cleric,sorcerer,warlock,wizard",
			truestrike: "bard,sorcerer,warlock,wizard",
			tsunami: "druid",
			unseenservant: "bard,warlock,wizard",
			vampirictouch: "warlock,wizard",
			viciousmockery: "bard",
			vitriolicsphere: "sorcerer,wizard",
			walloffire: "druid,sorcerer,wizard",
			wallofforce: "wizard",
			wallofice: "wizard",
			walloflight: "sorcerer,warlock,wizard",
			wallofsand: "wizard",
			wallofstone: "artificer,druid,sorcerer,wizard,artificerrevisited",
			wallofthorns: "druid",
			wallofwater: "druid,sorcerer,wizard",
			wardingbond: "cleric",
			wardingwind: "bard,druid,sorcerer,wizard",
			waterbreathing: "artificer,druid,ranger,sorcerer,wizard,artificer,artificerrevisited",
			waterwalk: "artificer,cleric,druid,ranger,sorcerer,artificer,artificerrevisited",
			waterysphere: "druid,sorcerer,wizard",
			web: "artificer,sorcerer,wizard",
			weird: "wizard",
			whirlwind: "druid,sorcerer,wizard",
			windwalk: "druid",
			windwall: "druid,ranger",
			wish: "sorcerer,wizard",
			witchbolt: "sorcerer,warlock,wizard",
			wordofradiance: "cleric",
			wordofrecall: "cleric",
			wrathofnature: "druid,ranger",
			wrathfulsmite: "paladin",
			zephyrstrike: "ranger",
			zoneoftruth: "bard,cleric,paladin"
		};
		if (game.settings.get("core", "language") === "ja") {
			list = {
				アストラルプロジェクション: "cleric,warlock,wizard",
				アニマルシェイプス: "druid",
				レジスタンス: "cleric,druid,artificer",
				マジックマウス: "bard,wizard,artificer",
				ブーミングブレード: "sorcerer,warlock,wizard,artificer",
				グリーンフレイムブレード: "warlock,wizard,artificer",
				ライトニングルアー: "sorcerer,warlock,wizard,artificer",
				ソードバースト: "sorcerer,warlock,wizard,artificer",
				アシッドスプラッシュ: "sorcerer,wizard,artificer",
				エイド: "cleric,paladin,artificer,ranger,bard",
				アラーム: "ranger,wizard,artificer",
				オルターセルフ: "sorcerer,wizard,artificer",
				アニマルフレンドシップ: "bard,druid,ranger",
				アニマルメッセンジャー: "bard,druid,ranger",
				アニメイトデッド: "cleric,wizard",
				アニメイトオブジェクツ: "bard,sorcerer,wizard,artificer",
				アンティライフシェル: "druid",
				アンティマジックフィールド: "cleric,wizard",
				アーケインアイ: "wizard,artificer",
				アーケインゲート: "sorcerer,warlock,wizard",
				アーケインロック: "wizard,artificer",
				アーマーオヴアガテュス: "warlock",
				アームズオヴハダル: "warlock",
				オーギュリイ: "wizard,druid,cleric",
				オーラオヴライフ: "cleric,paladin",
				オーラオヴピュアリティ: "cleric,paladin",
				オーラオヴヴァイタリティ: "druid,cleric,paladin",
				アウェイクン: "bard,druid",
				ベイン: "bard,cleric",
				バニッシングスマイト: "paladin",
				バニッシュメント: "cleric,paladin,sorcerer,warlock,wizard",
				バークスキン: "druid,ranger",
				ビーコンオヴホープ: "cleric",
				ビーストセンス: "druid,ranger",
				ビストウカース: "bard,cleric,wizard",
				ビグビーズハンド: "wizard,sorcerer,artificer",
				ブレードバリアー: "cleric",
				ブレードウォード: "bard,sorcerer,warlock,wizard",
				ブレス: "cleric,paladin",
				ブライト: "druid,sorcerer,warlock,wizard",
				ブランディングスマイト: "paladin",
				ブラインドネスデフネス: "bard,cleric,sorcerer,wizard",
				ブリンク: "sorcerer,wizard,artificer",
				ブラー: "sorcerer,wizard,artificer",
				ブラインディングスマイト: "paladin",
				バーニングハンズ: "sorcerer,wizard",
				コールライトニング: "druid",
				カームエモーションズ: "bard,cleric",
				チェインライトニング: "sorcerer,wizard",
				チャームパースン: "bard,druid,sorcerer,warlock,wizard",
				チルタッチ: "sorcerer,warlock,wizard",
				クロマティックオーブ: "sorcerer,wizard",
				サークルオヴデス: "sorcerer,warlock,wizard",
				サークルオヴパワー: "paladin",
				クレアヴォイアンス: "bard,cleric,sorcerer,wizard",
				クローン: "wizard",
				クラウドオヴダガーズ: "bard,sorcerer,warlock,wizard",
				クラウドキル: "sorcerer,wizard",
				カラースプレー: "sorcerer,wizard,bard",
				コマンド: "bard,cleric,paladin",
				コミューン: "cleric",
				コミューンウィズネイチャー: "druid,ranger",
				コンペルドデュエル: "paladin",
				コンプリヘンドランゲージズ: "bard,sorcerer,warlock,wizard",
				コンパルジョン: "bard",
				コーンオヴコールド: "sorcerer,wizard,druid",
				コンフュージョン: "bard,druid,sorcerer,wizard",
				カンジャーアニマルズ: "druid,ranger",
				カンジャーバラージ: "ranger",
				カンジャーセレスチャル: "cleric",
				カンジャーエレメンタル: "druid,wizard",
				カンジャーフェイ: "druid,warlock",
				カンジャーマイナーエレメンタルズ: "druid,wizard",
				カンジャーヴォレー: "ranger",
				カンジャーウッドランドビーイングズ: "druid,ranger",
				コンタクトアザープレイン: "warlock,wizard",
				コンテイジョン: "cleric,druid",
				コンティンジェンシィ: "wizard",
				コンティニュアルフレイム: "cleric,wizard,druid,artificer",
				コントロールウォーター: "cleric,druid,wizard",
				コントロールウェザー: "cleric,druid,wizard",
				コードンオヴアローズ: "ranger",
				カウンタースペル: "sorcerer,warlock,wizard",
				クリエイトフードアンドウォーター: "cleric,paladin,artificer",
				クリエイトアンデッド: "cleric,warlock,wizard",
				クリエイトオアデストロイウォーター: "cleric,druid",
				クリエイション: "sorcerer,wizard,artificer",
				クラウンオヴマッドネス: "bard,sorcerer,warlock,wizard",
				クルセイダーズマントル: "paladin",
				キュアウーンズ: "bard,cleric,druid,paladin,ranger,artificer",
				ダンシングライツ: "bard,sorcerer,wizard,artificer",
				ダークネス: "sorcerer,warlock,wizard",
				ダークヴィジョン: "druid,ranger,sorcerer,wizard,artificer",
				デイライト: "cleric,druid,paladin,ranger,sorcerer",
				デスウォード: "cleric,paladin",
				ディレイドブラストファイアーボール: "sorcerer,wizard",
				デミプレイン: "warlock,wizard,sorcerer",
				デストラクティヴウェイヴ: "paladin",
				ディスペルマジック: "bard,cleric,druid,paladin,sorcerer,warlock,wizard,artificer",
				ディテクトマジック: "bard,cleric,druid,paladin,ranger,sorcerer,wizard,artificer",
				ディテクトポイズンアンドディジーズ: "cleric,druid,paladin,ranger",
				ディテクトソウツ: "bard,sorcerer,wizard",
				ディメンジョンドア: "bard,sorcerer,warlock,wizard",
				ディスガイズセルフ: "bard,sorcerer,wizard,artificer",
				ディスインテグレイト: "sorcerer,wizard",
				ディスペルイーヴルアンドグッド: "cleric,paladin",
				ディヴィネーション: "wizard,druid,cleric",
				ディヴァインフェイヴァー: "paladin",
				ディヴァインワード: "cleric",
				ドミネイトビースト: "ranger,druid,sorcerer",
				ドミネイトモンスター: "bard,sorcerer,warlock,wizard",
				ドミネイトパースン: "bard,sorcerer,wizard",
				ドローミジズインスタントサモンズ: "wizard",
				ドリーム: "bard,warlock,wizard",
				ドルイドクラフト: "druid",
				アースクウェイク: "cleric,druid,sorcerer",
				エルドリッチブラスト: "warlock",
				エレメンタルウェポン: "paladin,ranger,druid,artificer",
				エンハンスアビリティ: "wizard,bard,cleric,ranger,druid,sorcerer,artificer",
				エンラージリデュース: "sorcerer,wizard,druid,bard,artificer",
				エンスネアリングストライク: "ranger",
				エンタングル: "druid,ranger",
				エンスロール: "bard,warlock",
				イセリアルネス: "bard,cleric,sorcerer,warlock,wizard",
				エヴァーズブラックテンタクルズ: "wizard",
				エクスペディシャスリトリート: "sorcerer,warlock,wizard,artificer",
				アイバイト: "bard,sorcerer,warlock,wizard",
				ファブリケイト: "wizard,artificer",
				フェアリーファイアー: "bard,druid,artificer",
				フォールスライフ: "sorcerer,wizard",
				フィアー: "bard,sorcerer,warlock,wizard",
				フェザーフォール: "bard,sorcerer,wizard,artificer",
				フィーブルマインド: "bard,druid,warlock,wizard",
				フェインデス: "bard,cleric,druid,wizard",
				ファインドファミリアー: "wizard",
				ファインドスティード: "paladin",
				ファインドトラップス: "cleric,druid,ranger",
				ファインドザパス: "bard,cleric,druid",
				フィンガーオヴデス: "sorcerer,warlock,wizard",
				ファイアーボルト: "sorcerer,wizard,artificer",
				ファイアーシールド: "wizard,sorcerer,druid",
				ファイアーストーム: "cleric,druid,sorcerer",
				ファイアーボール: "sorcerer,wizard",
				フレイムブレード: "druid,sorcerer",
				フレイムストライク: "cleric",
				フレイミングスフィアー: "druid,wizard,sorcerer",
				フレッシュトゥストーン: "warlock,wizard,sorcerer,druid",
				フライ: "sorcerer,warlock,wizard,artificer",
				フォッグクラウド: "druid,ranger,sorcerer,wizard",
				フォービダンス: "cleric",
				フォースケイジ: "bard,warlock,wizard",
				フォアサイト: "bard,druid,warlock,wizard",
				フリーダムオヴムーヴメント: "bard,cleric,druid,ranger,artificer",
				フレンズ: "bard,sorcerer,warlock,wizard",
				ガシアスフォーム: "sorcerer,warlock,wizard",
				ゲート: "cleric,sorcerer,wizard,warlock",
				ギアス: "bard,cleric,druid,paladin,wizard",
				ジェントルリポウズ: "cleric,paladin,wizard",
				ジャイアントインセクト: "druid",
				グリブネス: "bard,warlock",
				グローブオヴインヴァルナラビリティ: "sorcerer,wizard",
				グリフオヴウォーディング: "bard,cleric,wizard,artificer",
				グッドベリー: "druid,ranger",
				グラスピングヴァイン: "druid,ranger",
				グリース: "wizard,sorcerer,artificer",
				グレーターインヴィジビリティ: "bard,sorcerer,wizard",
				グレーターレストレーション: "ranger,bard,cleric,druid,artificer",
				ガーディアンオヴフェイス: "cleric",
				ガーズアンドウォーズ: "bard,wizard",
				ガイダンス: "cleric,druid,artificer",
				ガイディングボルト: "cleric",
				ガストオヴウィンド: "ranger,druid,sorcerer,wizard",
				ヘイルオヴソーンズ: "ranger",
				ハロウ: "cleric",
				ハリューサナトリテレイン: "bard,druid,warlock,wizard",
				ハーム: "cleric",
				ヘイスト: "sorcerer,wizard,artificer",
				ヒール: "cleric,druid",
				ヒーリングワード: "bard,cleric,druid",
				ヒートメタル: "bard,druid,artificer",
				ヘリッシュリビューク: "warlock",
				ヒーローズフィースト: "bard,cleric,druid",
				ヒロイズム: "bard,paladin",
				ヘクス: "warlock",
				ホールドモンスター: "bard,sorcerer,warlock,wizard",
				ホールドパースン: "bard,cleric,druid,sorcerer,warlock,wizard",
				ホーリィオーラ: "cleric",
				ハンガーオヴハダル: "warlock",
				ハンターズマーク: "ranger",
				ヒプノティックパターン: "bard,sorcerer,warlock,wizard",
				アイスストーム: "druid,sorcerer,wizard",
				アイデンティファイ: "bard,wizard,artificer",
				イリューソリィスクリプト: "bard,warlock,wizard",
				インプリズンメント: "warlock,wizard",
				インセンディエリクラウド: "sorcerer,wizard,druid",
				インフリクトウーンズ: "cleric",
				インセクトプレイグ: "cleric,druid,sorcerer",
				インヴィジビリティ: "bard,sorcerer,warlock,wizard,artificer",
				ジャンプ: "druid,ranger,sorcerer,wizard,artificer",
				ノック: "bard,sorcerer,wizard",
				レジェンドローア: "bard,cleric,wizard",
				レオムンズシークレットチェスト: "wizard,artificer",
				レオムンズタイニイハット: "bard,wizard",
				レッサーレストレーション: "bard,cleric,druid,paladin,ranger,artificer",
				レヴィテート: "sorcerer,wizard,artificer",
				ライト: "bard,cleric,sorcerer,wizard,artificer",
				ライトニングアロー: "ranger",
				ライトニングボルト: "sorcerer,wizard",
				ロケートアニマルズオアプランツ: "bard,druid,ranger",
				ロケートクリーチャー: "bard,cleric,druid,paladin,ranger,wizard",
				ロケートオブジェクト: "bard,cleric,druid,paladin,ranger,wizard",
				ロングストライダー: "bard,druid,ranger,wizard,artificer",
				メイジアーマー: "sorcerer,wizard",
				メイジハンド: "bard,sorcerer,warlock,wizard,artificer",
				マジックジャー: "wizard",
				マジックミサイル: "sorcerer,wizard",
				マジックサークル: "wizard,warlock,cleric,paladin",
				マジックウェポン: "paladin,wizard,sorcerer,ranger,artificer",
				メジャーイメージ: "bard,sorcerer,warlock,wizard",
				マスキュアウーンズ: "bard,cleric,druid",
				マスヒール: "cleric",
				マスヒーリングワード: "cleric,bard",
				マスサジェスチョン: "bard,sorcerer,warlock,wizard",
				メイズ: "wizard",
				メルドイントゥストーン: "cleric,ranger,druid",
				メルフスアシッドアロー: "wizard",
				メンディング: "bard,cleric,druid,sorcerer,wizard,artificer",
				メッセージ: "bard,sorcerer,wizard,artificer",
				ミーティアスウォーム: "sorcerer,wizard",
				マインドブランク: "bard,wizard",
				マイナーイリュージョン: "bard,sorcerer,warlock,wizard",
				ミラージュアーケイン: "bard,druid,wizard",
				ミラーイメージ: "sorcerer,warlock,wizard,bard",
				ミスリード: "bard,wizard,warlock",
				ミスティステップ: "sorcerer,warlock,wizard",
				モディファイメモリー: "bard,wizard",
				ムーンビーム: "druid",
				モルデンカイネンズフェイスフルハウンド: "wizard,artificer",
				モルデンカイネンズマグニフィセントマンション: "bard,wizard",
				モルデンカイネンズプライヴェートサンクトゥム: "wizard,artificer",
				モルデンカイネンズソード: "bard,wizard",
				ムーヴアース: "druid,sorcerer,wizard",
				ノンディテクション: "bard,ranger,wizard",
				ニストゥルズマジックオーラ: "wizard",
				オティルークスフリージングスフィアー: "wizard,sorcerer",
				オティルークスリジリアントスフィアー: "wizard,artificer",
				オットーズイレジスティブルダンス: "bard,wizard",
				パスウィズアウトトレイス: "druid,ranger",
				パスウォール: "wizard",
				ファンタズマルフォース: "bard,sorcerer,wizard",
				ファンタズマルキラー: "wizard",
				ファントムスティード: "wizard",
				プレイナーアライ: "cleric",
				プレイナーバインディング: "bard,cleric,druid,wizard,warlock",
				プレインシフト: "cleric,druid,sorcerer,warlock,wizard",
				プラントグロウス: "bard,druid,ranger",
				ポイズンスプレー: "druid,sorcerer,warlock,wizard,artificer",
				ポリモーフ: "bard,druid,sorcerer,wizard",
				パワーワードヒール: "bard,cleric",
				パワーワードキル: "bard,sorcerer,warlock,wizard",
				パワーワードスタン: "bard,sorcerer,warlock,wizard",
				プレイヤーオヴヒーリング: "cleric,paladin",
				プレスティディジテイション: "bard,sorcerer,warlock,wizard,artificer",
				プリズマティックスプレー: "sorcerer,wizard,bard",
				プリズマティックウォール: "wizard,bard",
				プロデュースフレイム: "druid",
				プログラムドイリュージョン: "bard,wizard",
				プロジェクトイメージ: "bard,wizard",
				プロテクションフロムエナジー: "cleric,druid,ranger,sorcerer,wizard,artificer",
				ディテクトイーヴルアンドグッド: "cleric,paladin",
				プロテクションフロムイーヴルアンドグッド: "cleric,paladin,ranger,wizard,druid,artificer",
				ピュアリファイフードアンドドリンク: "cleric,druid,paladin,artificer",
				レイズデッド: "bard,cleric,paladin",
				レアリーズテレパシックボンド: "wizard,bard",
				プロテクションフロムポイズン: "cleric,druid,paladin,ranger,artificer",
				レイオヴフロスト: "sorcerer,wizard,artificer",
				レイオヴシックネス: "sorcerer,wizard",
				リジェネレイト: "bard,cleric,druid",
				リインカーネイト: "druid",
				リムーヴカース: "cleric,paladin,warlock,wizard",
				リザレクション: "bard,cleric",
				リヴァースグラヴィティ: "druid,sorcerer,wizard",
				リヴィヴィファイ: "cleric,paladin,ranger,druid,artificer",
				ロープトリック: "wizard,artificer",
				セイクリッドフレイム: "cleric",
				サンクチュアリ: "cleric,artificer",
				レイオヴエンフィーブルメント: "warlock,wizard",
				スコーチングレイ: "sorcerer,wizard",
				スクライング: "bard,cleric,druid,warlock,wizard",
				シアリングスマイト: "paladin,ranger",
				シーインヴィジビリティ: "bard,sorcerer,wizard,artificer",
				シーミング: "bard,sorcerer,wizard",
				センディング: "bard,cleric,wizard",
				シクウェスター: "wizard",
				シェイプチェンジ: "druid,wizard",
				シャター: "bard,sorcerer,warlock,wizard",
				シールド: "sorcerer,wizard",
				シールドオヴフェイス: "cleric,paladin",
				シャレイリ: "druid",
				ショッキンググラスプ: "sorcerer,wizard,artificer",
				サイレンス: "bard,cleric,ranger",
				サイレントイメージ: "bard,sorcerer,wizard",
				シミュレイクラム: "wizard",
				スリープ: "bard,sorcerer,wizard",
				スリートストーム: "druid,sorcerer,wizard",
				スロー: "sorcerer,wizard,bard",
				スペアザダイイング: "cleric,artificer",
				スピークウィズアニマルズ: "bard,druid,ranger",
				スピークウィズデッド: "wizard,bard,cleric",
				スピークウィズプランツ: "bard,druid,ranger",
				スパイダークライム: "sorcerer,warlock,wizard,artificer",
				スパイクグロウス: "druid,ranger",
				スピリットガーディアンズ: "cleric",
				スピリチュアルウェポン: "cleric",
				スタガリングスマイト: "paladin",
				スティンキングクラウド: "bard,sorcerer,wizard",
				ストーンシェイプ: "cleric,druid,wizard,artificer",
				ストーンスキン: "druid,ranger,sorcerer,wizard,artificer",
				ストームオヴヴェンジャンス: "druid",
				サジェスチョン: "bard,sorcerer,warlock,wizard",
				サンビーム: "druid,sorcerer,wizard,cleric",
				サンバースト: "druid,sorcerer,wizard,cleric",
				スウィフトクウィヴァー: "ranger",
				シンボル: "bard,cleric,wizard,druid",
				ターシャーズヒディアスラフター: "bard,wizard",
				テレキネシス: "sorcerer,wizard",
				テレパシー: "wizard",
				テレポート: "bard,sorcerer,wizard",
				テレポーテーションサークル: "bard,sorcerer,wizard,warlock",
				テンサーズフローティングディスク: "wizard",
				ソーマタージー: "cleric",
				ソーンウィップ: "druid,artificer",
				サンダラススマイト: "paladin",
				サンダーウェイヴ: "bard,druid,sorcerer,wizard",
				タイムストップ: "sorcerer,wizard",
				タンズ: "bard,cleric,sorcerer,warlock,wizard",
				トランスポートヴァイアプランツ: "druid",
				ツリーストライド: "druid,ranger",
				トゥルーポリモーフ: "bard,warlock,wizard",
				トゥルーリザレクション: "cleric,druid",
				トゥルーシーイング: "bard,cleric,sorcerer,warlock,wizard",
				トゥルーストライク: "bard,sorcerer,warlock,wizard",
				ツナミ: "druid",
				アンシーンサーヴァント: "bard,warlock,wizard",
				ヴァンピリックタッチ: "warlock,wizard,sorcerer",
				ヴィシャスモッカリィ: "bard",
				ウォールオヴファイアー: "druid,sorcerer,wizard",
				ウォールオヴフォース: "wizard",
				ウォールオヴアイス: "wizard",
				ウォールオヴストーン: "druid,sorcerer,wizard,artificer",
				ウォールオヴソーンズ: "druid",
				ウォーディングボンド: "cleric,paladin",
				ウォーターブリージング: "druid,ranger,sorcerer,wizard,artificer",
				ウォーターウォーク: "cleric,druid,ranger,sorcerer,artificer",
				ウェブ: "sorcerer,wizard,artificer",
				ウィアード: "wizard,warlock",
				ウィンドウォーク: "druid",
				ウィンドウォール: "druid,ranger",
				ウィッシュ: "sorcerer,wizard",
				ウィッチボルト: "sorcerer,warlock,wizard",
				ワードオヴリコール: "cleric",
				ラスフルスマイト: "paladin",
				ゾーンオヴトゥルース: "bard,cleric,paladin",
				インヴェスティチャーオヴストーン: "wizard,warlock,sorcerer,druid",
				フロストバイト: "wizard,warlock,sorcerer,druid,artificer",
				アガナザーズスコーチャー: "wizard,sorcerer",
				エネミーズアバウンド: "wizard,warlock,sorcerer,bard",
				ボーンズオヴジアース: "druid",
				アーストレマー: "wizard,sorcerer,druid,bard",
				スキルエンパワーメント: "wizard,sorcerer,bard,artificer",
				メルフスマイニュートミーティアズ: "wizard,sorcerer",
				テンサーズトランスフォーメーション: "wizard",
				タイニーサーヴァント: "wizard,artificer",
				コントロールフレイムズ: "wizard,sorcerer,druid",
				コーズフィアー: "wizard,warlock",
				プライモーディアルウォード: "druid",
				インヴァルナラビリティ: "wizard",
				サモングレーターデーモン: "wizard,warlock",
				スキャター: "wizard,warlock,sorcerer",
				アビーダルジムズホリッドウィルティング: "wizard,sorcerer",
				ウォールオヴサンド: "wizard",
				ダストデヴィル: "wizard,sorcerer,druid",
				パイロテクニクス: "wizard,sorcerer,bard,artificer",
				シェイプウォーター: "wizard,sorcerer,druid",
				マインドスパイク: "wizard,warlock,sorcerer",
				ファインドグレータースティード: "paladin",
				テンプルオヴザゴッズ: "cleric",
				スカイライト: "wizard,druid,bard,artificer",
				ガーディアンオヴネイチャー: "ranger,druid",
				ウォータリースフィアー: "wizard,sorcerer,druid",
				マスポリモーフ: "wizard,sorcerer,bard",
				シャドウオヴモイル: "warlock",
				ネガティヴエナジーフラッド: "wizard,warlock",
				トウルザデッド: "wizard,warlock,cleric",
				クラウンオヴスターズ: "wizard,warlock,sorcerer",
				インヴェスティチャーオヴウィンド: "wizard,warlock,sorcerer,druid",
				ガスト: "wizard,sorcerer,druid",
				ワードオヴレイディアンス: "cleric",
				インフェステイション: "wizard,warlock,sorcerer,druid",
				サンダークラップ: "wizard,warlock,sorcerer,druid,bard,artificer",
				エナヴェイション: "wizard,warlock,sorcerer",
				ヒーリングスピリット: "ranger,druid",
				タイダルウェイヴ: "wizard,sorcerer,druid",
				キャットナップ: "wizard,sorcerer,bard,artificer",
				スネア: "wizard,ranger,druid,artificer",
				ビーストボンド: "ranger,druid",
				サイキックスクリーム: "wizard,warlock,sorcerer,bard",
				シャドウブレード: "wizard,warlock,sorcerer",
				コントロールウィンズ: "wizard,sorcerer,druid",
				イモレーション: "wizard,sorcerer",
				アースバインド: "wizard,warlock,sorcerer,druid",
				マッドニングダークネス: "wizard,warlock",
				ウォールオヴライト: "wizard,warlock,sorcerer",
				ダンスマカブル: "wizard,warlock",
				ゼファーストライク: "ranger",
				イリューソリィドラゴン: "wizard",
				エラプティングアース: "wizard,sorcerer,druid",
				フレイムアローズ: "wizard,sorcerer,ranger,druid,artificer",
				シナプティックスタティック: "wizard,warlock,sorcerer,bard",
				マクシミリアンズアースングラスプ: "wizard,sorcerer",
				ケイオスボルト: "sorcerer",
				マイティフォートレス: "wizard",
				マジックストーン: "warlock,druid,artificer",
				ドルイドグローヴ: "druid",
				ファーステップ: "wizard,warlock,sorcerer",
				ホーリィウェポン: "paladin,cleric",
				インファーナルコーリング: "wizard,warlock",
				クリエイトホムンクルス: "wizard",
				ウォールオヴウォーター: "wizard,sorcerer,druid",
				セレモニー: "paladin,cleric",
				ソウルケイジ: "wizard,warlock",
				スチールウィンドストライク: "wizard,ranger",
				エレメンタルベイン: "wizard,warlock,druid,artificer",
				メイルストロム: "druid",
				ライフトランスファランス: "wizard,cleric",
				チャームモンスター: "wizard,warlock,sorcerer,druid,bard",
				インヴェスティチャーオヴフレイム: "wizard,warlock,sorcerer,druid",
				カタパルト: "wizard,sorcerer,artificer",
				パワーワードペイン: "wizard,warlock,sorcerer",
				サモンレッサーデーモンズ: "wizard,warlock",
				サンダーステップ: "wizard,warlock,sorcerer",
				ワールウィンド: "wizard,sorcerer,druid",
				モールドアース: "wizard,sorcerer,druid",
				シックニングレイディアンス: "wizard,warlock,sorcerer",
				ストームスフィアー: "wizard,sorcerer",
				アイスナイフ: "wizard,sorcerer,druid",
				インヴェスティチャーオヴアイス: "wizard,warlock,sorcerer,druid",
				アブソーブエレメンツ: "wizard,sorcerer,ranger,druid,artificer",
				ヴィトリオリックスフィアー: "wizard,sorcerer",
				ドラゴンズブレス: "wizard,sorcerer",
				スニロックススノーボールスウォーム: "wizard,sorcerer",
				プライマルサヴェジリィ: "druid",
				メンタルプリズン: "wizard,warlock,sorcerer",
				ウォーディングウィンド: "wizard,sorcerer,druid,bard",
				トランスミュートロック: "wizard,druid,artificer",
				クリエイトボンファイアー: "wizard,warlock,sorcerer,druid,artificer",
				ラスオヴネイチャー: "ranger,druid",
				ドーン: "wizard,cleric",
				ディソナントウィスパーズ: "bard",
				ターシャズヒディアスラフター: "bard,wizard",
				アンティパシーシンパシー: "wizard,bard,druid",
				マインドスリヴァー: "wizard,warlock,sorcerer",
				ターシャズコースティックブリュー: "wizard,sorcerer,artificer",
				サモンビースト: "ranger,druid",
				ターシャズマインドウィップ: "wizard,sorcerer",
				インテレクトフォートレス: "wizard,warlock,sorcerer,bard,artificer",
				サモンアンデッド: "wizard,warlock",
				サモンシャドウスポーン: "wizard,warlock",
				サモンフェイ: "wizard,warlock,ranger,druid",
				スピリットシュラウド: "wizard,warlock,cleric,paladin",
				サモンアベレイション: "wizard,warlock",
				サモンエレメンタル: "wizard,ranger,druid",
				サモンコンストラクト: "wizard,artificer",
				サモンセレスチャル: "cleric,paladin",
				サモンフィーンド: "wizard,warlock",
				ターシャスアザーワールドリィガイズ: "wizard,warlock,sorcerer",
				ドリームオヴザブルーヴェイル: "wizard,warlock,sorcerer,bard",
				ブレードオヴディザスター: "wizard,warlock,sorcerer"
			};
		}
		return list;
	}

	static packList = {
		burglar: [
			"Burglar's Pack",
			"Backpack",
			"Ball Bearings",
			"String",
			"Bell",
			"Candle",
			"Crowbar",
			"Hammer",
			"Piton",
			"Hooded Lantern",
			"Oil Flask",
			"Rations",
			"Tinderbox",
			"Waterskin",
			"Hempen Rope (50 ft.)"
		],
		diplomat: [
			"Diplomat's Pack",
			"Chest",
			"Map or Scroll Case",
			"Fine Clothes",
			"Ink Bottle",
			"Ink Pen",
			"Lamp",
			"Oil Flask",
			"Paper",
			"Perfume",
			"Sealing Wax",
			"Soap"
		],
		dungeoneer: [
			"Dungeoneer's Pack",
			"Backpack",
			"Crowbar",
			"Hammer",
			"Piton",
			"Torch",
			"Tinderbox",
			"Rations",
			"Waterskin",
			"Hempen Rope (50 ft.)"
		],
		entertainer: [
			"Entertainer's Pack",
			"Backpack",
			"Bedroll",
			"Costume Clothes",
			"Candle",
			"Rations",
			"Waterskin",
			"Disguise Kit"
		],
		explorer: [
			"Explorer's Pack",
			"Backpack",
			"Bedroll",
			"Mess Kit",
			"Tinderbox",
			"Torch",
			"Rations",
			"Waterskin",
			"Hempen Rope (50 ft.)"
		],
		monsterhunter: [
			"Monster Hunter's Pack",
			"Chest",
			"Crowbar",
			"Hammer",
			"Wooden Stake",
			"Holy Symbol",
			"Flask of Holy Water",
			"Manacles",
			"Steel Mirror",
			"Oil Flask",
			"Tinderbox",
			"Torch"
		],
		priest: [
			"Priest's Pack",
			"Backpack",
			"Blanket",
			"Candle",
			"Tinderbox",
			"Alms Box",
			"Block of Incense",
			"Censor",
			"Vestments",
			"Rations",
			"Waterskin"
		],
		scholar: [
			"Scholar's Pack",
			"Backpack",
			"Book of Lore",
			"Ink Bottle",
			"Ink Pen",
			"Parchment",
			"Bag of Sand",
			"Small Knife"
		]
	};

	static subClasses = {
		artificer: ["Alchemist", "Gunsmith"],
		barbarian: [
			"Ancesstrial Guardian",
			"Battlerager",
			"Berserker",
			"Storm Herald",
			"Totem Warriro",
			"Zealot"
		],
		bard: ["Eloquence", "Glamour", "Lore", "Swords", "Valor", "Whispers"],
		cleric: [
			"Arcana",
			"Death",
			"Forge",
			"Grave",
			"Knowledge",
			"Life",
			"Light",
			"Nature",
			"Order",
			"Tempest",
			"Trickery",
			"War Domain"
		],
		druid: ["Dreams", "Land", "Moon", "Shepherd", "Spores"],
		fighter: [
			"Arcane Archer",
			"Battle Master",
			"Cavalier",
			"Champion",
			"Echo Knight",
			"Eldritch Knight",
			"Samurai"
		],
		monk: [
			"Drunken Master",
			"Four Elements",
			"Kensei",
			"Long Death",
			"Open Hand",
			"Shadow",
			"Sun Soul"
		],
		paladin: [
			"Ancients",
			"Conquest",
			"Crown",
			"Devotion",
			"Glory",
			"Oathbreaker",
			"Redemption",
			"Vengeance"
		],
		ranger: [
			"Beast Master",
			"Gloom Stalker",
			"Horizon Walker",
			"Hunter",
			"Monster Slayer"
		],
		rogue: [
			"Arcane Trickster",
			"Assassin",
			"Inquisitive",
			"Mastermind",
			"Scout",
			"Swashbuckler",
			"Thief"
		],
		sorcerer: ["Divine Soul", "Draconic", "Shadow", "Storm", "Wild"],
		warlock: [
			"Archfey",
			"Celestial",
			"Fiend",
			"Great Old One",
			"Hexblade",
			"Undying"
		],
		wizard: [
			"Abjuration",
			"Bladesinging",
			"Chronurgy",
			"Conjuration",
			"Divination",
			"Énchantment",
			"Evocation",
			"Graviturgy",
			"Illusion",
			"Necromancy",
			"Transmutation",
			"War Magic"
		]
	};
}
